### PR TITLE
:sparkles: add framewise displacement metric to outliers detector

### PR DESCRIPTION
**Pull request by vanandrew**
This PR adds the framewise displacement metric to the outliers detector.

It uses the SimpleITK library to do the framewise alignment. Currently the parameters for this registration are hard coded, though I think it might be better to have these as inputs to registration function.

### CODE REVIEW

**Comment by vanandrew** [comment]
@cindyhfls @takeshibx

Might be good to test these changes on your machines before I merge them.

You can create a branch from this pull request by doing the following:

```
git fetch upstream pull/13/head:pull_13
git checkout pull_13
```
`git fetch upstream pull/[pull request #]/head:[branch_name]` will fetch this pull request to your local repo and allow you to switch to the branch under `[branch_name]`

Try running `python scripts/find_outliers.py data` and let me know if you get any errors.

**Comment by cindyhfls** [comment]
I don't have simpleitk installed, and when I try to do "conda install simpleitk" I got:
PackagesNotFoundError: The following packages are not available from current channels:

  - simpleitk

**Comment by vanandrew** [comment]
Looks like simpleitk isn't available with conda. You may need to install it with pip. Checkout this guide:  

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages

**Comment by cindyhfls** [comment]
okay the code worked for me

**Comment by vanandrew** [comment]
@cindyhfls Great!

Added an update to the analysis plan, [hyperlinking the pull requests to each implemented feature](https://github.com/vanandrew/diagnostics-NIL/blob/framewise_displacement/analysis_plan.md).

**Comment by cindyhfls** [comment]
Are we still going to look at the raw images with fsl?

**Comment by vanandrew** [comment]
I think we can do that once we've implemented some techniques to assess the data.

@takeshibx Have you tried this PR on your end yet? Does it work for you?

**Comment by vanandrew** [comment]
Awesome will merge this in.

**Pull request merged**
